version: "3.3"
networks:
   opencbr-database:
services:
    db:
        image: mysql/mysql-server:5.6
        container_name: opencbr-db-mysql
        volumes:
            - ./openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
        env_file:
            - db.env
        ports:
            - "3307:3306"
        networks:
          - opencbr-database
    webapp:
        image: tomcat:7-jre7-alpine
        container_name: openshr-tomcat
        depends_on:
            - db
        volumes:
            - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./modules:/root/.OpenMRS/modules
        ports:
            - "8081:8080"
        networks:
            - opencbr-database